#!/usr/bin/env node
/* build_craft_check.js — emit ONE self-contained .sql file that exercises
   docs/sql/workshop_craft.sql against a scratch Postgres.

   CI can't run this (plain `node tools/check_*.js`, no services), and
   workshop_craft.sql is ~600 lines of logic that decides whether a crafted item
   exists — so it gets a real integration test you can run by hand.

   Build:  node tools/sql/build_craft_check.js > /tmp/craft_check.sql
   Run:    psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f /tmp/craft_check.sql
           (any throwaway database — it creates its own players table and a
            stub auth.uid(); never point it at a real project)

   It stitches together, in order:
     1. tools/sql/craft_harness.sql — stand-ins for the Supabase pieces
        (auth.uid, public.players, app._lock_state / _write_state, a test clock)
     2. the real helper functions the file leans on, lifted verbatim out of the
        other docs/sql files so the test can't drift from production
     3. docs/sql/workshop_craft.sql itself
     4. tools/sql/craft_smoke.sql — the assertions                            */
"use strict";
const fs = require("fs"), path = require("path");

const root = path.join(__dirname, "..", "..");
const read = p => fs.readFileSync(path.join(root, p), "utf8");

// Real dependencies, in dependency order.
const DEPS = [
  ["docs/sql/market_price.sql", "market.imul32"],
  ["docs/sql/market_price.sql", "market.fnv1a"],
  ["docs/sql/market_price.sql", "market.u01"],
  ["docs/sql/market_price.sql", "market.seed_hash"],
  ["docs/sql/phase2_missions_bazaar.sql", "app.ship_def"],
  ["docs/sql/phase2_missions_bazaar.sql", "app.fleet_cap"],
  ["docs/sql/phase2_missions_bazaar.sql", "app.item_value"],
  ["docs/sql/phase2_missions_bazaar.sql", "app.make_ship"],
  ["docs/sql/equip_persist.sql", "app._ship_slots"],
  ["docs/sql/equip_persist.sql", "app._merge_ships"],
  ["docs/sql/phase1_players.sql", "app._in_transit"],
  ["docs/sql/phase3_pull_prestige.sql", "app._merge_industries"],
  ["docs/sql/phase3_pull_prestige.sql", "app._merge_expeditions"],
  ["docs/sql/phase3_pull_prestige.sql", "app._merge_extractors"],
];

// A definition runs from its `create or replace function <name>(` line to the
// next line that is exactly `$$;`.
function extract(file, fn) {
  const lines = read(file).split("\n");
  const head = new RegExp(`^create or replace function ${fn.replace(".", "\\.")}\\s*\\(`);
  const start = lines.findIndex(l => head.test(l.trim()));
  if (start < 0) throw new Error(`not found: ${fn} in ${file}`);
  const end = lines.indexOf("$$;", start);
  if (end < 0) throw new Error(`no terminator for ${fn} in ${file}`);
  return lines.slice(start, end + 1).join("\n");
}

const out = [
  "-- GENERATED by tools/sql/build_craft_check.js — do not edit.",
  "-- Throwaway databases only: this creates public.players and a stub auth.uid().",
  // Roles are cluster-wide, so this may already exist (Supabase always has it).
  "do $r$ begin if not exists (select 1 from pg_roles where rolname = 'authenticated')\n" +
  "  then create role authenticated; end if; end $r$;",
  read("tools/sql/craft_harness.sql"),
  "-- ---- real helpers lifted from the other docs/sql files ----",
  ...DEPS.map(([f, fn]) => extract(f, fn)),
  read("docs/sql/workshop_craft.sql"),
  read("tools/sql/craft_smoke.sql"),
];
process.stdout.write(out.join("\n\n") + "\n");
