#!/usr/bin/env python3
"""gen_sprite_manifest.py — build js/sprite-manifest.js from the sprite_assets/ tree.

The walkable-hub map editor (js/hubedit.js) shows a drag-and-drop palette of the
uploaded sprites. Phase 1 is a static site that must run from file:// as well as
GitHub Pages, so we can't fetch() a directory listing at runtime — instead we bake
the file list into a plain-<script> global. Re-run this whenever sprite_assets/
changes:  python3 tools/gen_sprite_manifest.py
"""
import json
import os

def _q(s):
    return json.dumps(s)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "sprite_assets")
OUT = os.path.join(ROOT, "js", "sprite-manifest.js")
EXT = (".png", ".gif", ".jpg", ".jpeg", ".webp")

groups = []
for cat in sorted(os.listdir(SRC)):
    d = os.path.join(SRC, cat)
    if not os.path.isdir(d):
        continue
    files = sorted(f for f in os.listdir(d) if f.lower().endswith(EXT))
    if not files:
        continue
    paths = ["sprite_assets/%s/%s" % (cat, f) for f in files]
    groups.append((cat, paths))

lines = [
    "/* sprite-manifest.js — GENERATED by tools/gen_sprite_manifest.py. Do not edit by hand.",
    "   Grouped list of the uploaded sprite_assets/ files, exposed as a plain global so the",
    "   hub map editor's drag-and-drop palette works on file:// (no directory fetch).        */",
    "window.SPRITE_ASSETS = [",
]
for cat, paths in groups:
    lines.append("  { cat: " + _q(cat) + ", files: [")
    for p in paths:
        lines.append("    " + _q(p) + ",")
    lines.append("  ] },")
lines.append("];")

with open(OUT, "w") as fh:
    fh.write("\n".join(lines) + "\n")

total = sum(len(p) for _, p in groups)
print("wrote %s — %d categories, %d sprites" % (OUT, len(groups), total))
