#!/usr/bin/env python3
"""gen_media_manifest.py — build js/media-manifest.js from assets/broadcast/ + assets/bgm/.

Phase 1 is a static site that must run from file:// as well as GitHub Pages, so
we can't list a directory at runtime. Instead the file names ARE the config and
this bakes them into a plain-<script> global. Re-run after adding files:

    python3 tools/gen_media_manifest.py

Broadcast: the channel is the file name with any trailing number stripped, so
news.png / news1.png / news_2.png all land on the "news" channel. A channel only
shows up on the Broadcast screen if some TV_SHOWS entry (js/flavor.js) uses it —
"news" is special-cased by Ui.showNews.

BGM: every audio file becomes a track, ordered by file name (prefix with 01_,
02_ … to set the shipped order). A leading sort prefix is dropped from the
display name: 02_abandoned_outpost.mp3 -> "Abandoned Outpost".
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "js", "media-manifest.js")
IMG_EXT = (".png", ".gif", ".jpg", ".jpeg", ".webp")
AUDIO_EXT = (".mp3", ".ogg", ".wav", ".webm", ".m4a")


def _q(s):
    return json.dumps(s)


def _natural(name):
    """Sort key so news2 comes before news10."""
    return [int(p) if p.isdigit() else p for p in re.split(r"(\d+)", name.lower())]


def _listdir(rel, exts):
    d = os.path.join(ROOT, rel)
    if not os.path.isdir(d):
        return []
    files = [f for f in os.listdir(d) if f.lower().endswith(exts) and not f.startswith(".")]
    return sorted(files, key=_natural)


def broadcast_pools():
    """{channel: [url, ...]} keyed by file name minus any trailing number."""
    pools = {}
    for f in _listdir("assets/broadcast", IMG_EXT):
        stem = os.path.splitext(f)[0]
        channel = re.sub(r"[ _-]*\d+$", "", stem).strip(" _-").lower() or stem.lower()
        pools.setdefault(channel, []).append("assets/broadcast/" + f)
    return pools


def bgm_tracks():
    tracks = []
    for f in _listdir("assets/bgm", AUDIO_EXT):
        stem = os.path.splitext(f)[0]
        name = re.sub(r"^\d+[._\- ]+", "", stem)          # drop 01_ ordering prefix
        name = re.sub(r"[_\-]+", " ", name).strip()
        name = " ".join(w[:1].upper() + w[1:] for w in name.split()) or stem
        tracks.append({"url": "assets/bgm/" + f, "name": name})
    return tracks


pools = broadcast_pools()
tracks = bgm_tracks()

lines = [
    "/* media-manifest.js — GENERATED by tools/gen_media_manifest.py. Do not edit by hand.",
    "   File names are the config: drop a file in assets/broadcast/ or assets/bgm/, re-run",
    "   the generator, and it shows up in-game. Broadcast frames merge into the same",
    "   LOCAL_ASSET_POOLS keys admins can override from Supabase (Admin -> Images), so a",
    "   live override still wins. BGM_TRACKS is the whole playlist — git is the source of",
    "   truth; players pick their own order/start track in Settings -> Music.            */",
    "",
    "window.LOCAL_ASSET_POOLS = Object.assign(window.LOCAL_ASSET_POOLS || {}, {",
]
for channel in sorted(pools):
    urls = ", ".join(_q(u) for u in pools[channel])
    lines.append("  " + _q("broadcast:" + channel) + ": [" + urls + "],")
lines.append("});")
lines.append("")
lines.append("window.BGM_TRACKS = [")
for t in tracks:
    lines.append("  { url: " + _q(t["url"]) + ", name: " + _q(t["name"]) + " },")
lines.append("];")

with open(OUT, "w") as fh:
    fh.write("\n".join(lines) + "\n")

frames = sum(len(v) for v in pools.values())
print("wrote %s — %d broadcast channels / %d frames, %d bgm tracks"
      % (OUT, len(pools), frames, len(tracks)))
